apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: production-hpa
  namespace: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-production
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
